### ISSUE TITLE
Homepage is blank

### ISSUE THREAD

**Issue by anotherduckling** [wopian/kitsu-season-trends#691]
![image](https://github.com/wopian/kitsu-season-trends/assets/57977673/5f4e3482-4e8a-4d5c-97a6-7fecdf6eec2c)

**Comment by wopian** [comment]
Thanks for reporting this! Looks like a React update bricked the front-end at some point (I want to get rid of React at some point but don't have the time).

Will revert it back to an older React dependency and freeze the version.

**Comment by wopian** [comment]
Should be back online now: https://season.moe/2023/autumn
